FROM nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3.8 \
        python3-pip \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "app.py"]
