env:
  PYTHONUNBUFFERED: "true"

services:
  - name: web
    build:
      context: .
      dockerfile: Dockerfile
    env:
      - NVIDIA_VISIBLE_DEVICES=all
    port: 80
    start_command: uvicorn main:app --host 0.0.0.0 --port 80 --workers 1
